// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjDaWC2_PGxu8e9mxwNavGPFoZu1y6F6E',
    appId: '1:453393533989:web:796ce10aa74145cb5783cc',
    messagingSenderId: '453393533989',
    projectId: 'edtech-chat-34156',
    authDomain: 'edtech-chat-34156.firebaseapp.com',
    storageBucket: 'edtech-chat-34156.firebasestorage.app',
    measurementId: 'G-64RP3L6686',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJolD3q_AwnmSZj945MMxeWQf4ttvEoiw',
    appId: '1:453393533989:android:1bf2a488aeaf889b5783cc',
    messagingSenderId: '453393533989',
    projectId: 'edtech-chat-34156',
    storageBucket: 'edtech-chat-34156.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbZ0qQYoUCNSXRYsorV_VGondV3PwoO1k',
    appId: '1:453393533989:ios:96a51ef7369330e95783cc',
    messagingSenderId: '453393533989',
    projectId: 'edtech-chat-34156',
    storageBucket: 'edtech-chat-34156.firebasestorage.app',
    iosBundleId: 'com.example.edtechChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbZ0qQYoUCNSXRYsorV_VGondV3PwoO1k',
    appId: '1:453393533989:ios:96a51ef7369330e95783cc',
    messagingSenderId: '453393533989',
    projectId: 'edtech-chat-34156',
    storageBucket: 'edtech-chat-34156.firebasestorage.app',
    iosBundleId: 'com.example.edtechChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjDaWC2_PGxu8e9mxwNavGPFoZu1y6F6E',
    appId: '1:453393533989:web:73c55ed64c8c673f5783cc',
    messagingSenderId: '453393533989',
    projectId: 'edtech-chat-34156',
    authDomain: 'edtech-chat-34156.firebaseapp.com',
    storageBucket: 'edtech-chat-34156.firebasestorage.app',
    measurementId: 'G-Z9QGFCHX4F',
  );
}
